name: CI/CD Minikube TLS Deployment & Test

on:
  push:
    branches: ["main"]

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Start Minikube
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      # 2.1️⃣ Enable Ingress addon
      - name: Enable Minikube Ingress
        run: minikube addons enable ingress

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t my-app:latest .

      # 4️⃣ Load image into Minikube
      - name: Import image into Minikube
        run: minikube image load my-app:latest

      # 5️⃣ Create TLS Secret
      - name: Create TLS Secret
        run: |
          kubectl create secret tls my-app-tls \
            --cert=tls/my-app.crt \
            --key=tls/my-app.key \
            --dry-run=client -o yaml | kubectl apply -f -

      # 6️⃣ Deploy Kubernetes resources
      - name: Deploy Deployment, Service, Ingress
        run: |
          kubectl apply -f k8s/Deployment.yaml
          kubectl apply -f k8s/Service.yaml
          kubectl apply -f k8s/Ingress.yaml

      # 7️⃣ Map my-app.local inside the runner
      - name: Map my-app.local to Minikube IP (runner only)
        run: |
          echo "$(minikube ip) my-app.local" | sudo tee -a /etc/hosts

      # 8️⃣ Verify pods, services, ingress
      - name: Verify Kubernetes resources
        run: |
          kubectl get pods -o wide
          kubectl get svc -o wide
          kubectl get ingress -o wide

      # 9️⃣ Test HTTPS connection inside runner
      - name: Test HTTPS access
        run: |
          # Ignore certificate errors since it's self-signed
          curl -k https://my-app.local
